Add support for mobile devices, integrate sentry
crust-lab/cra-template-crustlab pull request #12
Opened 2022-07-27 16:21 UTC by skusnierz

2022-08-08 10:24 UTC, rafalkociatkiewicz commented on template/src/hooks/useWindowSize.ts
> +    window.addEventListener('resize', updateSize);
add debounce

2022-08-08 10:31 UTC, rafalkociatkiewicz commented on template/src/pages/login/components/Form.tsx
> +  @media ${getMediaQueryBreakpoint('xs')} {
const baseSizesCzyCos = css` XYZ `;

const StyledButton = styled(Button)`
${baseSizesCzyCos}
`;

2022-08-08 13:48 UTC, rafalkociatkiewicz commented on template/src/templates/main/components/mobile/Navbar.tsx
> +interface NavbarProps {
wydzielić to aby można było użyć w Menu, SideMenu, AnyOtherMenu

2022-08-08 13:49 UTC, rafalkociatkiewicz commented on template/src/theme/globalStyle.ts
> +        color: ${getColor('text01')} !important;;
';;' why?

2022-08-08 13:51 UTC, rafalkociatkiewicz requested changes
Have fun fixing that

2022-08-08 17:11 UTC, rafalkociatkiewicz approved these changes

2022-08-09 06:12 UTC, spiewak commented on README.md
> +|	└───components	reusable common components go here
I believe that it's a problem with formatting but `components`, `contexts` and `ThemeContext.tsx` should be considered as assets.

2022-08-09 06:14 UTC, spiewak commented on README.md
> +|	└───helpers reusable common utility functions/libs go here
Another problem with formatting `forms` should not contain `pages`, `home`, `services` etc.

2022-08-09 06:17 UTC, spiewak commented on README.md
> +Sentry configuration is done in **index.tsx** the file, Sentry is only run on a production environment.
Sentry configuration is done in **index.tsx** file. Sentry is run only in a production environment.

2022-08-09 06:18 UTC, spiewak commented on README.md
> +In order for sentry to correctly display the error stack trace, we need to uplod the source map. To do this, we can use a previously prepared script **sentryCreateRelease.js** and run this npm comman
In order to correctly display the error stack trace, we need to upload the source map. To do this, we can use a previously prepared script **sentryCreateRelease.js** and run this npm command :

2022-08-10 07:50 UTC, skusnierz commented on README.md
> +|	└───components	reusable common components go here
Fixed

2022-08-10 07:50 UTC, skusnierz commented on README.md
> +|	└───helpers reusable common utility functions/libs go here
Fixed

2022-08-10 07:56 UTC, spiewak commented
@skusnierz If there are no more comments, merge please :-)

2022-08-10 07:58 UTC, merged